version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: orit-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}    
    ports:
      - '3306:3306'
    volumes:
      - ./.mysql-data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./.redis-data:/data

volumes:
  mysql_data:
  redis_data:
